[35;21m2022-11-21 14:44:36,454 [0m[30;1m[ERROR]: [0m[31;21min mu32.log (core_ws.py:719): Stop running due to exception: [Errno 111] Connect call failed ('10.3.141.1', 8002).[0m
[35;21m2022-11-21 14:44:49,754 [0m[30;1m[ERROR]: [0m[31;21min mu32.log (core_ws.py:719): Stop running due to exception: MuException:  [Listening command failed. Server 10.3.141.1:8002 said:  Listening service request failed: There is no running task. Megamicro is not recording].[0m
[35;21m2022-11-21 14:58:23,059 [0m[30;1m[ERROR]: [0m[31;21min mu32.log (core_ws.py:719): Stop running due to exception: sent 1011 (unexpected error) keepalive ping timeout; no close frame received.[0m
